export const featuredItems = [
    {
      title: 'SD Showcase Gives Back',
      imageUrl: '/images/hr-professionals.webp',
      alt: 'sample',
      description: 'News write-ups offer a great way to let clients know about new products and services, events, awards, and more!',
      slug: "sd-showcase-gives-back",
      date: "March 02, 2024",
      creator: "Creator",
    },
    {
      title: 'Hiro Wilson Ready for SDS',
      imageUrl: '/images/hr-professionals.webp',
      alt: 'sample',
      description: 'News write-ups offer a great way to let clients know about new products and services, events, awards, and more!',
      slug: "hiro-wilson-ready-for-sds",
      date: "January 20, 2024",
      creator: "Creator",
    },
    {
      title: '5k Attendees for SDS 2025',
      imageUrl: '/images/hr-professionals.webp',
      alt: 'sample',
      description: 'News write-ups offer a great way to let clients know about new products and services, events, awards, and more!',
      slug: "5k-attendees-for-sds-2025",
      date: "February 18, 2024",
      creator: "Creator",
    },
    {
      title: 'SD Showcase Gives Back',
      imageUrl: '/images/hr-professionals.webp',
      alt: 'sample',
      description: 'News write-ups offer a great way to let clients know about new products and services, events, awards, and more!',
      slug: "sd-showcase-gives-back",
      date: "February 18, 2024",
      creator: "Creator",
    },
    {
      title: 'Hiro Wilson Ready for SDS',
      imageUrl: '/images/hr-professionals.webp',
      alt: 'sample',
      description: 'News write-ups offer a great way to let clients know about new products and services, events, awards, and more!',
      slug: "hiro-wilson-ready-for-sds",
      date: "January 20, 2024",
      creator: "Creator",
    },
    {
      title: '5k Attendees for SDS 2025',
      imageUrl: '/images/hr-professionals.webp',
      alt: 'sample',
      description: 'News write-ups offer a great way to let clients know about new products and services, events, awards, and more!',
      slug: "5k-attendees-for-sds-2025",
      date: "January 21, 2024",
      creator: "Creator",
    },
    {
      title: 'Hiro Wilson Ready for SDS',
      imageUrl: '/images/hr-professionals.webp',
      alt: 'sample',
      description: 'News write-ups offer a great way to let clients know about new products and services, events, awards, and more!',
      slug: "hiro-wilson-ready-for-sds",
      date: "April 20, 2024",
      creator: "Creator",
    },
    {
      title: '5k Attendees for SDS 2025',
      imageUrl: '/images/hr-professionals.webp',
      alt: 'sample',
      description: 'News write-ups offer a great way to let clients know about new products and services, events, awards, and more!',
      slug: "5k-attendees-for-sds-2025",
      date: "January 1, 2024",
      creator: "Creator",
    },
];